### ISSUE TITLE
Traceback (most recent call last):   File "train_models.py", line 72, in <module>     train(CIFAR(), "models/cifar", [64, 64, 128, 128, 256, 256], num_epochs=50)   File "train_models.py", line 58, in train     validation_data=(data.validation_data, data.validation_labels), AttributeError: 'CIFAR' object has no attribute 'validation_data'

### ISSUE THREAD

**Issue by aspnetcs** [IBM/UAE#1]
Traceback (most recent call last):
  File "train_models.py", line 72, in <module>
    train(CIFAR(), "models/cifar", [64, 64, 128, 128, 256, 256], num_epochs=50)
  File "train_models.py", line 58, in train
    validation_data=(data.validation_data, data.validation_labels),
AttributeError: 'CIFAR' object has no attribute 'validation_data'

how to fix it under tensorflow 1.14

**Comment by chiayi-hsu** [comment]
I have already modified the File "setup_cifar.py". 
You can run ```python train_models.py``` again and the error should be fixed.
